version: 3
workdir: .

allow:
  depOnAnyVendor: false
  deepScan: false

components:
  cmd:                        { in: cmd/** }
  bootstrap:                  { in: internal }
  feature_can_i_deploy:       { in: internal/features/can_i_deploy }
  feature_create_environment: { in: internal/features/create_environment }
  feature_create_participant: { in: internal/features/create_participant }
  feature_publish_contract:   { in: internal/features/publish_contract/** }
  feature_record_deployment:  { in: internal/features/record_deployment }
  feature_rename_participant: { in: internal/features/rename_participant }
  components:                 { in: internal/components }
  repository:                 { in: internal/repository }
  compatibility_checker:      { in: internal/compatibility_checker }
  contract_differ:            { in: internal/contract_differ }
  mapper:                     { in: internal/mapper/** }
  model:                      { in: internal/model }
  common:                     { in: internal/common }
  dsl:                        { in: internal/dsl }
  validations:                { in: internal/validations }
  pkg:                        { in: pkg/** }
  tests:                      { in: tests/** }

vendors:
  fiber:          { in: [github.com/gofiber/fiber/v3, github.com/gofiber/fiber/v3/**] }
  pgx:            { in: [github.com/jackc/pgx/v5, github.com/jackc/pgx/v5/**] }
  guregu_null:    { in: [github.com/guregu/null, github.com/guregu/null/**] }
  yaml:           { in: [github.com/goccy/go-yaml, github.com/goccy/go-yaml/**] }
  godotenv:       { in: [github.com/joho/godotenv, github.com/joho/godotenv/**] }
  testify:        { in: [github.com/stretchr/testify, github.com/stretchr/testify/**] }
  testcontainers: { in: [github.com/testcontainers/testcontainers-go, github.com/testcontainers/testcontainers-go/**] }

deps:
  cmd:
    mayDependOn: [bootstrap]
    canUse: [godotenv]

  bootstrap:
    mayDependOn:
      - components
      - feature_can_i_deploy
      - feature_create_environment
      - feature_create_participant
      - feature_publish_contract
      - feature_record_deployment
      - feature_rename_participant
    canUse: [fiber]

  feature_can_i_deploy:
    mayDependOn: [components, repository, compatibility_checker, contract_differ, mapper, model, common, dsl, validations]
    canUse: [fiber, guregu_null]
  feature_create_environment:
    mayDependOn: [components, repository, compatibility_checker, contract_differ, mapper, model, common, dsl, validations]
    canUse: [fiber, guregu_null]
  feature_create_participant:
    mayDependOn: [components, repository, compatibility_checker, contract_differ, mapper, model, common, dsl, validations]
    canUse: [fiber, guregu_null]
  feature_publish_contract:
    mayDependOn: [feature_publish_contract, components, repository, compatibility_checker, contract_differ, mapper, model, common, dsl, validations]
    canUse: [fiber, guregu_null, yaml]
  feature_record_deployment:
    mayDependOn: [components, repository, compatibility_checker, contract_differ, mapper, model, common, dsl, validations]
    canUse: [fiber, guregu_null]
  feature_rename_participant:
    mayDependOn: [components, repository, compatibility_checker, contract_differ, mapper, model, common, dsl, validations]
    canUse: [fiber, guregu_null]

  components:
    mayDependOn: [model, common, pkg]
    canUse: [fiber, pgx]
  repository:
    mayDependOn: [model, common, dsl, validations]
    canUse: [pgx, guregu_null]
  compatibility_checker:
    mayDependOn: [model, common, dsl, validations]
    canUse: [guregu_null]
  contract_differ:
    mayDependOn: [model, common, dsl, validations]
    canUse: [guregu_null]
  mapper:
    mayDependOn: [mapper, model, common, dsl, validations]

  model:
    canUse: [guregu_null]
  dsl:
    mayDependOn: [common]

  pkg:
    canUse: [pgx]

  tests:
    mayDependOn:
      - bootstrap
      - components
      - feature_can_i_deploy
      - feature_create_environment
      - feature_create_participant
      - feature_publish_contract
      - feature_record_deployment
      - feature_rename_participant
      - repository
      - compatibility_checker
      - contract_differ
      - mapper
      - model
      - common
      - dsl
      - validations
      - pkg
    canUse: [fiber, pgx, guregu_null, yaml, testify, testcontainers]
